server:
  servlet:
    context-path: /libraryservice
  port: 5000

aws:
  endpoint: http://dynamodb.eu-west-2.amazonaws.com:4566
  tableName: libraryServiceCollectionTest

---

spring:
  config:
    activate:
      on-profile: local
aws:
  endpoint: https://localhost.localstack.cloud:4566


