server:
  servlet:
    context-path: /libraryservice
  port: 5000

aws:
  endpoint: http://dynamodb.eu-west-2.amazonaws.com:4566
  tableName: libraryServiceCollectionTest

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/itemdb
    username: root
    password: nnCE6mpp!


---

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/itemdb
    username: root
    password: password123!
  config:
    activate:
      on-profile: local
aws:
  endpoint: https://localhost.localstack.cloud:4566


